version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - ./uploads:/app/uploads
      - ./media:/app/media
    ports:
      - "11002:8000"
    image: conveterapp
    container_name: conveterapp
    command: 
      - /bin/bash
      - -c
      - |
        python3 ./manage.py migrate
        python3 ./manage.py collectstatic --noinput
        python3 ./manage.py runserver 0.0.0.0:8000
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "11001:80"  # Host port 11001 mapped to Nginx container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles  # Ensure static files are available
      - ./uploads:/app/uploads
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'booking'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'user123'
      MYSQL_ROOT_PASSWORD: 'user123'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'db123'
    ports:
      - '8088:80'
    depends_on:
      - db
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
# user manager -> db, api autthen (login, logout, register)(user, pass)

# strite -> api connect strite, api, paymenbt.