# Generated by Django 3.2.25 on 2024-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_password_set',
            field=models.BooleanField(default=False),
        ),
    ]
